version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.0
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    _PIP_ADDITIONAL_REQUIREMENTS: 'apache-airflow-providers-postgres boto3 pandas'   # <-- NOVO
    MINIO_ENDPOINT: http://minio:9000                                                # <-- NOVO
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}                                              # <-- NOVO
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}                                       # <-- NOVO
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./src/ingestion/dags:/opt/airflow/dags/ingestion 
  depends_on:
    postgres:
      condition: service_healthy
  networks:
    - pipeline_net

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data
     - ./sql/northwind_schema.sql:/docker-entrypoint-initdb.d/northwind_schema.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    networks:
      - pipeline_net

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT_API}:9000"
      - "${MINIO_PORT_CONSOLE}:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
    networks:
      - pipeline_net

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init && airflow users create --username $${AIRFLOW_ADMIN_USER} --password $${AIRFLOW_ADMIN_PASSWORD} --firstname Admin --lastname User --role Admin --email admin@admin.com
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "${AIRFLOW_PORT}:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "${SPARK_MASTER_UI_PORT}:8080"
      - "${SPARK_MASTER_PORT}:7077"
    volumes:
      - ./src:/opt/spark-apps
    networks:
      - pipeline_net

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
    ports:
      - "${SPARK_WORKER_UI_PORT}:8081"
    volumes:
      - ./src:/opt/spark-apps
    depends_on:
      - spark-master
    networks:
      - pipeline_net

  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    ports:
      - "${SUPERSET_PORT}:8088"
    volumes:
      - superset_data:/app/superset_home
    networks:
      - pipeline_net

volumes:
  postgres_data:
  minio_data:
  superset_data:

networks:
  pipeline_net:
    driver: bridge
